[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
  # Required for backtraces (esp-backtrace)
  "-C", "force-frame-pointers",
]

[unstable]
build-std = ["core", "alloc"]

[env]
ESP_LOG = "info"
